// *****************************************************************************
// * This file is part of supercell-wx-grib.  Licensed under the GNU General
// * Public License v3.  See the COPYING file for the full license text.
// *****************************************************************************

// GENERATED by tools/derive_idx_selectors.py from real RRFS and RTMA files --
// do not edit by hand; re-run the tool after adding a product (a unit test
// fails for an RRFS or RTMA product missing from the table).

#include <scwx/qt/manager/grib_field_selectors.hpp>

#include <map>
#include <utility>

namespace scwx::qt::manager::grib_fields
{

namespace
{

using Key = std::pair<map::GribCategory, std::string>;

// Positional {parameter, level} pairs: naming each member would only add noise
// to a generated table.
// NOLINTBEGIN(modernize-use-designated-initializers)
const std::map<Key, ProductFields> kProductFields_ {
   // Rtma
   {{map::GribCategory::Rtma, "2m Temperature"},
    {{{"TMP", "2 m above ground"}}, {}}},
   {{map::GribCategory::Rtma, "2m Dewpoint"},
    {{{"DPT", "2 m above ground"}}, {}}},
   {{map::GribCategory::Rtma, "10m Wind Speed"},
    {{{"WIND", "10 m above ground"}}, {}}},
   {{map::GribCategory::Rtma, "10m Wind Gust"},
    {{{"GUST", "10 m above ground"}}, {}}},
   {{map::GribCategory::Rtma, "Visibility"}, {{{"VIS", "surface"}}, {}}},
   // Rrfs
   {{map::GribCategory::Rrfs, "Mean Sea Level Pressure"},
    {{{"MSLET", "mean sea level"}}, {}}},
   {{map::GribCategory::Rrfs, "Lightning Threat"},
    {{{"LTNG", "entire atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "STP (Fixed-Layer)"},
    {{{"HGT", "surface"},
      {"CAPE", "surface"},
      {"CIN", "surface"},
      {"HLCY", "1000-0 m above ground"},
      {"HGT", "level of adiabatic condensation from sfc"},
      {"VUCSH", "0-6000 m above ground"},
      {"VVCSH", "0-6000 m above ground"}},
     {}}},
   {{map::GribCategory::Rrfs, "Simulated Reflectivity (1km AGL)"},
    {{{"REFD", "1000 m above ground"}}, {}}},
   {{map::GribCategory::Rrfs, "Simulated Reflectivity (4km AGL)"},
    {{{"REFD", "4000 m above ground"}}, {}}},
   {{map::GribCategory::Rrfs, "Simulated Reflectivity (-10C level)"},
    {{{"REFD", "263 K level"}}, {}}},
   {{map::GribCategory::Rrfs, "VIL"},
    {{{"VIL", "entire atmosphere (considered as a single layer)"}}, {}}},
   {{map::GribCategory::Rrfs, "Visibility"}, {{{"VIS", "surface"}}, {}}},
   {{map::GribCategory::Rrfs, "Wind Gust"}, {{{"GUST", "surface"}}, {}}},
   {{map::GribCategory::Rrfs, "Surface Pressure"}, {{{"PRES", "surface"}}, {}}},
   {{map::GribCategory::Rrfs, "Precipitation Rate"},
    {{{"PRATE", "surface"}}, {}}},
   {{map::GribCategory::Rrfs, "1-Hour Precipitation"},
    {{{"APCP", "surface"}}, {}}},
   {{map::GribCategory::Rrfs, "Total Precipitation"},
    {{{"APCP", "surface"}}, {}}},
   {{map::GribCategory::Rrfs, "500mb Height"}, {{{"HGT", "500 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "500mb Temperature"}, {{{"TMP", "500 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "700mb Temperature"}, {{{"TMP", "700 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "500mb Wind Speed"},
    {{{"UGRD", "500 mb"}, {"VGRD", "500 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "1000mb Height"}, {{{"HGT", "1000 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "1000mb Wind Speed"},
    {{{"UGRD", "1000 mb"}, {"VGRD", "1000 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "850mb Height"}, {{{"HGT", "850 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "850mb Wind Speed"},
    {{{"UGRD", "850 mb"}, {"VGRD", "850 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "700mb Height"}, {{{"HGT", "700 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "700mb Wind Speed"},
    {{{"UGRD", "700 mb"}, {"VGRD", "700 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "300mb Height"}, {{{"HGT", "300 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "300mb Wind Speed"},
    {{{"UGRD", "300 mb"}, {"VGRD", "300 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "250mb Height"}, {{{"HGT", "250 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "250mb Wind Speed"},
    {{{"UGRD", "250 mb"}, {"VGRD", "250 mb"}}, {}}},
   {{map::GribCategory::Rrfs, "SHIP"},
    {{{"HGT", "surface"},
      {"CAPE", "180-0 mb above ground"},
      {"SPFH", "2 m above ground"},
      {"VUCSH", "0-6000 m above ground"},
      {"VVCSH", "0-6000 m above ground"},
      {"HGT", "0C isotherm"}},
     {{"TMP", "500 mb"},
      {"TMP", "700 mb"},
      {"HGT", "500 mb"},
      {"HGT", "700 mb"}}}},
   {{map::GribCategory::Rrfs, "Boundary Layer Height"},
    {{{"HPBL", "surface"}}, {}}},
   {{map::GribCategory::Rrfs, "Precipitable Water"},
    {{{"PWAT", "entire atmosphere (considered as a single layer)"}}, {}}},
   {{map::GribCategory::Rrfs, "Ceiling"}, {{{"CEIL", "cloud ceiling"}}, {}}},
   {{map::GribCategory::Rrfs, "Total Cloud Cover"},
    {{{"TCDC", "entire atmosphere (considered as a single layer)"}}, {}}},
   {{map::GribCategory::Rrfs, "Low Cloud Cover"},
    {{{"LCDC", "low cloud layer"}}, {}}},
   {{map::GribCategory::Rrfs, "Mid Cloud Cover"},
    {{{"MCDC", "middle cloud layer"}}, {}}},
   {{map::GribCategory::Rrfs, "High Cloud Cover"},
    {{{"HCDC", "high cloud layer"}}, {}}},
   {{map::GribCategory::Rrfs, "SBCAPE"}, {{{"CAPE", "surface"}}, {}}},
   {{map::GribCategory::Rrfs, "SBCIN"}, {{{"CIN", "surface"}}, {}}},
   {{map::GribCategory::Rrfs, "MUCAPE"},
    {{{"CAPE", "180-0 mb above ground"}}, {}}},
   {{map::GribCategory::Rrfs, "MUCIN"},
    {{{"CIN", "180-0 mb above ground"}}, {}}},
   {{map::GribCategory::Rrfs, "0-1km SRH"},
    {{{"HLCY", "1000-0 m above ground"}}, {}}},
   {{map::GribCategory::Rrfs, "0-3km SRH"},
    {{{"HLCY", "3000-0 m above ground"}}, {}}},
   {{map::GribCategory::Rrfs, "0-6km Shear"},
    {{{"VUCSH", "0-6000 m above ground"}, {"VVCSH", "0-6000 m above ground"}},
     {}}},
   {{map::GribCategory::Rrfs, "10m Wind Speed"},
    {{{"UGRD", "10 m above ground"}, {"VGRD", "10 m above ground"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 7 (3.9um)"},
    {{{"SBTA167", "top of atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 8 (6.2um)"},
    {{{"SBTA168", "top of atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 9 (6.9um)"},
    {{{"SBTA169", "top of atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 10 (7.3um)"},
    {{{"SBTA1610", "top of atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 11 (8.4um)"},
    {{{"SBTA1611", "top of atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 12 (9.6um)"},
    {{{"SBTA1612", "top of atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 13 (10.3um)"},
    {{{"SBTA1613", "top of atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 14 (11.2um)"},
    {{{"SBTA1614", "top of atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 15 (12.3um)"},
    {{{"SBTA1615", "top of atmosphere"}}, {}}},
   {{map::GribCategory::Rrfs, "Sat Band 16 (13.3um)"},
    {{{"SBTA1616", "top of atmosphere"}}, {}}},
};

const std::vector<scwx::util::grib_idx::FieldSelector> kHodographFields_ {
   {"UGRD", "10 m above ground"},
   {"VGRD", "10 m above ground"},
   {"UGRD", "30 m above ground"},
   {"VGRD", "30 m above ground"},
   {"UGRD", "50 m above ground"},
   {"VGRD", "50 m above ground"},
   {"UGRD", "80 m above ground"},
   {"VGRD", "80 m above ground"},
   {"UGRD", "100 m above ground"},
   {"VGRD", "100 m above ground"},
   {"UGRD", "160 m above ground"},
   {"VGRD", "160 m above ground"},
   {"UGRD", "320 m above ground"},
   {"VGRD", "320 m above ground"},
   {"UGRD", "305 m above mean sea level"},
   {"VGRD", "305 m above mean sea level"},
   {"UGRD", "457 m above mean sea level"},
   {"VGRD", "457 m above mean sea level"},
   {"UGRD", "610 m above mean sea level"},
   {"VGRD", "610 m above mean sea level"},
   {"UGRD", "914 m above mean sea level"},
   {"VGRD", "914 m above mean sea level"},
   {"UGRD", "1524 m above mean sea level"},
   {"VGRD", "1524 m above mean sea level"},
   {"UGRD", "1829 m above mean sea level"},
   {"VGRD", "1829 m above mean sea level"},
   {"UGRD", "2134 m above mean sea level"},
   {"VGRD", "2134 m above mean sea level"},
   {"UGRD", "2743 m above mean sea level"},
   {"VGRD", "2743 m above mean sea level"},
   {"UGRD", "3658 m above mean sea level"},
   {"VGRD", "3658 m above mean sea level"},
   {"UGRD", "4572 m above mean sea level"},
   {"VGRD", "4572 m above mean sea level"},
   {"HGT", "surface"}};

const std::vector<scwx::util::grib_idx::FieldSelector> kWindBarbFields_ {
   {"WDIR", "10 m above ground"},
   {"WIND", "10 m above ground"},
   {"GUST", "10 m above ground"}};
// NOLINTEND(modernize-use-designated-initializers)

} // namespace

const ProductFields* FieldsFor(map::GribCategory  category,
                               const std::string& displayName)
{
   const auto it = kProductFields_.find({category, displayName});
   return it == kProductFields_.cend() ? nullptr : &it->second;
}

const std::vector<scwx::util::grib_idx::FieldSelector>& HodographFields()
{ return kHodographFields_; }

const std::vector<scwx::util::grib_idx::FieldSelector>& WindBarbFields()
{ return kWindBarbFields_; }

} // namespace scwx::qt::manager::grib_fields
